name: my_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  photo_view: ^0.11.1
  flutter_statusbarcolor: ^0.2.3
  bubble_tab_indicator: '^0.1.5'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/vehicles/
    - lib/assets/images/map/
    - lib/assets/images/weapons/assault-rifles/

  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: lib/assets/fonts/AlegreyaSans-Bold.ttf
        - asset: lib/assets/fonts/AlegreyaSans-Regular.ttf
        - asset: lib/assets/fonts/AlegreyaSans-Light.ttf
